In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [54]:
iris = datasets.load_iris()
X = iris.data  
y = iris.target
name = iris.feature_names

In [55]:
iris_data = datasets.load_iris()

df = pd.DataFrame(data=iris_data.data, 
                  columns=iris_data.feature_names)
df['label'] = iris_data.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   label              150 non-null    int32
dtypes: float64(4), int32(1)
memory usage: 5.4 KB

In [57]:
X = df.iloc[::, :-2]
y = df.iloc[::, -1]

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
model = GaussianNB()
y_pred = model.fit(X_train, y_train).predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 2, 2, 1, 2, 1, 1, 1, 1])

In [59]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8666666666666667

In [60]:
X_test[:1]

     sepal length (cm)  sepal width (cm)  petal length (cm)
114                5.8               2.8                5.1

In [61]:
np.around(model.predict_proba(X_test[:1]),2)

array([[0.  , 0.46, 0.54]])